### ISSUE TITLE
Help Installation Tutorial

### ISSUE THREAD

**Issue by ThorManager** [ByConity/ByConity#1020]
Please tell me how to access CNCH_ Configure multiple servers, tso, and daemons in config_ Manager, resource_ Manager, hdfs_ Nnproxy

Previously, due to a configuration error, the daemon manager reported an error, but now the cnch has been modified_ Is the config file still reporting the previous error? Why?
![image](https://github.com/ByConity/ByConity/assets/96821352/c470a784-1fef-4766-b704-9c39eceac915)
And one server node couldn't start without understanding where the error was
![image](https://github.com/ByConity/ByConity/assets/96821352/23a72fa8-e3aa-4174-a6f8-346733958f76)
![image](https://github.com/ByConity/ByConity/assets/96821352/abb53f6c-e8a3-4a27-9f4f-8ccd2ffa5d19)

**Comment by ThorManager** [comment]
thank you very much

**Comment by yuanzhubi** [comment]
![image](https://github.com/ByConity/ByConity/assets/25676580/0915b22b-a3ec-4ee6-82a1-7da4988d769a)
I think the server could not start is due to the listening host configuration problem? Could you show the configuration of "listen_host" and check whether your system supports IPv6 visiting?
![image](https://github.com/ByConity/ByConity/assets/25676580/7d1efa25-17ca-4e57-a18b-7f68a420cdcb)
