### ISSUE TITLE
General questions about ByConity team plans

### ISSUE THREAD

**Issue by UnamedRus** [ByConity/ByConity#41]
Hi,

First I want to say thanks for open sourcing it.

It seems, that it have in production quite a bit of features, which doesn't production ready in ClickHouse, or not yet implemented:
1. Transactions
2. CBO, HBO and other analyzers and optimizations.
3. Statistics
4. Resource Pools & management
5. Complete separation of Storage & Compute
6. Shared Metadata Storage
7. Exactly once Kafka tables (with auto scaling?)
8. Refresh for Materialized Views 
9. DELETE FROM (lightweight deletes?)
10. Shuffle Join (probably?)
11. New aggregate and regular functions
12. Numa aware compute? 
13. Unique key support in MergeTree (BTW, there is ongoing PR with the same name (but not sure about implementation details) to ClickHouse, https://github.com/ClickHouse/ClickHouse/pull/44534 it is related somehow to you? (I see, that it's being made by Tencent guys, and ByConity from ByteDance, but any chance))

And, i'm interested in some questions about plans of your team.

1. Are you are going to try keep it up with recent ClickHouse releases?
1.1 Probably even contribute some features from ByConity back to ClickHouse, in order to make total diff smaller and easier to manage? (ie having different Transaction implementation in ClickHouse and ByConity, will make live harder)
1.2 It is going to be based on ClickHouse in future, or rewritten over time in completely separate project?
2. Am i right, that it's being used in ByteHouse? (i've heard, that it had much older version of ClickHouse, but this one seems pretty recent ~21.8)

BTW, it would be great to have complete list of distinguish features compared to ClickHouse

**Comment by chenxing-xc** [comment]
1. We have to say it's hard to keep up with recent ClickHouse release as ClickHouse iterate very fast and refactor very frequently.
Idealy, we want to embrace community effort help us to achieve this goal. 
  For the question whether this project will still built on ClickHouse, I think it is as we reuse some ClickHouse's conceptions in the 
  projgect e.g. operator/MergeTreeData etc. But ByConity want to be general data warehouse project with performance, scalability and able to 
  handle complex workload. That's why we add many components here.
2. yes, ByteHouse core engine will be based on ByConity this year. Honestly it is on the old codebase now, and we will switch to the new codebase soon. 
We upgraded ClickHouse code base to 21.8 in order to open source byconity so that other developers might be easy to join.
