### ISSUE TITLE
ClickHouse compatibility (S3 and ReplicatedMergeTree)

### ISSUE THREAD

**Issue by lazywei** [ByConity/ByConity#724]
## Question

We're currently using ClickHouse's ReplicatedMergeTree and we're doing ingestion via
```
INSERT INTO foo SELECT * FROM s3('....')
```

My first question is do we have a corresponding external table function? I did a quick search into the codebase and it seems there is a `CnchS3(...)` table function but not quite sure if it is the same thing as ClickHouse's S3 table function.

My second question is do we still need any sort of replication if we are using `cnch_default_s3` as the default storage policy? Is it true that we can on-demand spin up more `byconity-server` statefulset to query the same table because the storage is decoupled from the compute? Will the new `byconity-server` instance replicate metadata from peers automatically?

Thanks

**Comment by dmthuc** [comment]
Hi @lazywei , thank you for the question. The CnchS3 is the same as s3 table function in clickhouse. And we don't need any sort of replication for that case because the data is stored in remote disk and not local. It is true that we can on-demand spin up more `byconity-worker` not `server` to query the same table because storage is decoupled from the compute. Currently we store meta data in FoundationDB, a dedicated component to store metadata that can scale independently so no need to replicated the metadata as well.

**Comment by dmthuc** [comment]
Hi @lazywei , I didn't know that issue in ClickHouse. For insert query I think you can control the part size of both ClickHouse or ByConity by using Settings `min_insert_block_size_rows` and `min_insert_block_size_bytes`. Unless you have fine grain partition key, those settings is the settings control Squash operator that squash smaller blocks into big blocks before insert to disks

**Comment by dmthuc** [comment]
Hi @lazywei, I think the point is better to have the part size big enough to avoid unnecessary merge, improve insert performance and improve select query performance. In ByConity for CnchMergeTree engine, we use system.cnch_parts. You can take a look into a list of our system table in [here]( https://github.com/ByConity/ByConity/blob/master/doc/system_table.md). And the squash operator is like you said is to keep data in memory a little while until the size is big enough before push to disk. And these settings is there quite a while ago in ClickHouse. You can look at this document. https://clickhouse.com/docs/knowledgebase/Insert_select_settings_tuning
