### ISSUE TITLE
byconity select query cost time much longer than clickhouse because of  part metadata load

### ISSUE THREAD

**Issue by blueskygzhz** [ByConity/ByConity#830]
When do select query, byconity need load parts metadata every time. Because of this, ByConity read query cost much longer time than ClickHouse.

For example:
In the below query,  select query cost 375ms, but load part metadata cost 300ms, even worse  part metadata need to be loaded every time.

![2db37faca6806279b61d6aec521ba02](https://github.com/ByConity/ByConity/assets/147569085/f54ca296-df24-4538-ba6e-2ee4883f22c4)

**Comment by dmthuc** [comment]
Hi @blueskygzhz , I see that the number of parts is 507. Usually, the cost of metadata cost should be small compare to the cost of query cost. Can you check the size of the visible data part in table system.cnch_parts? I suspect the merge process have issue so that it is unable to merge data part hence the number of data parts is high compare to the total size

**Comment by dmthuc** [comment]
The query to get the total size is 
```
select sum(bytes), sum(rows) from system.cnch_parts where database = 'test' and active = 1 and table = 'table_name'
```
