### ISSUE TITLE
brpc logs EPOLLOUT warnings very frequently

### ISSUE THREAD

**Issue by dogauzuncukoglu** [ByConity/ByConity#990]
## Question

We see a warning log very frequently in our byconity cluster deployed to kubernetes. Here is the warning log in question

```
2023.12.20 14:45:40.620143 [ 61 ] {} brpc: [../contrib/incubator-brpc/src/brpc/socket.cpp:1274]Fail to wait EPOLLOUT of fd=609: Connection timed out
```

Our cluster looks like this:
<img width="505" alt="Screenshot 2023-12-20 at 17 56 06" src="https://github.com/ByConity/ByConity/assets/100557431/3c83afbd-58a2-4a32-b97e-b7e446701b26">

For reference this warning message is logged around ~32k times per hour. If I am not mistaken logs are exclusively coming from workers (both default and write)

My questions are:

1. Is this expected? Should we ignore this warning?
2. If it is not expected can you suggest where we can check to gather more information?

**Comment by wordhardqi** [comment]
@jenrryyou could u help on this

**Comment by jenrryyou** [comment]
This could be due to us preserving some brpc Channels(cllient) in our connection pool. When a Channel is set to Failed, it will attempt to reconnect regularly (controlled by the BPRC's Gflags Flag health_check_interval, default is 3 seconds). If it continues to fail, this message will keep appearing, but this usually doesn't need attention. We will eventually disable the auto-reconnect feature by default, as this has already been handled in the higher-level logic.

**Comment by dogauzuncukoglu** [comment]
thanks @jenrryyou for the explanation. Closing the issue.
